# Generated by Django 2.2.5 on 2023-11-27 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=1000)),
                ('symbol', models.FileField(null=True, upload_to='documents/', verbose_name='Symbol')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
        migrations.CreateModel(
            name='Voter_Detail',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=1000)),
                ('voter_id', models.FileField(null=True, upload_to='documents/', verbose_name='Voter Id')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2023, 11, 27, 12, 26, 39, 553528, tzinfo=utc), verbose_name='Posted Date')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Candidate_Detail')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Voter_Detail')),
            ],
        ),
    ]
